# Generated by Django 5.0.6 on 2024-06-18 10:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='cat-default.jpg', null=True, upload_to='categories_images/')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='food-default.jpg', upload_to='foods/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذا ها',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='restrnt-default.jpg', upload_to='restaurants_imgs/%Y/%m/')),
                ('order_count', models.IntegerField(default=0)),
                ('count_view', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('open_close', models.BooleanField(blank=True, null=True)),
                ('rating_count', models.IntegerField(default=0)),
                ('sum_rating', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='restaurant.address')),
                ('categories', models.ManyToManyField(related_name='restaurants', to='restaurant.category')),
                ('restaurant_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'رستوران',
                'verbose_name_plural': 'رستوران ها',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='food-default.jpg', upload_to='foods/')),
                ('meal', models.CharField(choices=[('breakfast', 'صبحانه'), ('common', 'وعده غذایی اصلی'), ('beverages', 'نوشیدنی'), ('desserts', 'سالاد '), ('others', 'منو')], default='others', max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('size', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.food')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منو ز',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازات',
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
