# Generated by Django 4.2 on 2024-06-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='cat-default.jpg', null=True, upload_to='categories_images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restrnt-default.jpg', upload_to='restaurants_imgs/%Y/%m/'),
        ),
    ]
