# Generated by Django 4.2 on 2024-06-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_1',
            new_name='image_11',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image_2',
            new_name='image_22',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image_3',
            new_name='image_33',
        ),
    ]
