# Generated by Django 5.0.6 on 2024-06-13 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_category_image_alter_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='discount',
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='food-default.jpg', upload_to='foods/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='food-default.jpg', upload_to='foods/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal',
            field=models.CharField(choices=[('breakfast', 'صبحانه'), ('common', 'وعده غذایی اصلی'), ('beverages', 'نوشیدنی'), ('desserts', 'سالاد '), ('others', 'منو')], default='others', max_length=50),
        ),
    ]
