# Generated by Django 4.2 on 2024-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='open_close',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
