# Generated by Django 5.0.6 on 2024-06-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'کانتکت',
                'verbose_name_plural': ' کانتکت ها',
            },
        ),
    ]
